### ISSUE TITLE
Move Github issues link to the top of the document

### ISSUE THREAD

**Issue by andybak** [ryankemper/writings#19]
I suspect that many people - those with the strongest objections - won't make it to the end of your piece.

I think it's commendable to create a piece of writing that has a bug tracker and if you are genuinely open to correction that's quite laudable (and unusual).

However because this is so out of the ordinary you should signpost it very clearly at the start if you want any real engagement from your strongest critics.

**Comment by ryankemper** [comment]
This is a great point. I’ll make that change later today and circle back to
reference the commit here.
