### ISSUE TITLE
Remove patronizing language

### ISSUE THREAD

**Issue by 0atman** [ryankemper/writings#8]
Hard pass on this, dawg:

>Finally, the intent of this article is to use the most precise language possible, while still remaining largely understandable to a citizen of average intelligence and education level. Indeed, we have truly succeeded if this article is understandable to those who (through no fault of their own) may have significantly below average intelligence and/or educational attainment.

This sounds really patronizing, lose it.

**Comment by ryankemper** [comment]
I totally see why it comes off that way. Ironically, I added the "(through no fault of their own)" part to avoid it coming off as negative, but it totally had the opposite effect.

I didn't nuke the whole thing, but I think the new version (0d62f51) should be better. Please re-open if you think it still sounds off, etc
